% -------------------------------------------------------------------
%  Generated by MATLAB on 9-Nov-2017 11:36:10
%  MATLAB version: 9.3.0.713579 (R2017b)
% -------------------------------------------------------------------
saveVarsMat = load('cropmiaspatch.mat');

MIAS = saveVarsMat.MIAS; % <1x1 table> unsupported class

ans = 117;

clear saveVarsMat;
